name: Increase Major Version

on:
  push:
    branches:
      - main

jobs:
  increase-major-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Application Version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
         change_path: "src/service"
      - name: Database Version
        id: db-version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          major_pattern: "(MAJOR-DB)"
          minor_pattern: "(MINOR-DB)"
          change_path: "src/migrations"
