name: Increase Major Version

on:
  push:
    branches:
      - main

jobs:
  increase-major-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git Version
        id: semvar
        uses: paulhatch/semantic-version@v5.0.3
        with:
         version_format: "${major}.${minor}.${patch}"
         
      - name: Print version 2
        run: |
          echo ${{ steps.semvar.outputs.version }} ${{ steps.semvar.outputs.version_tag }} ${{ steps.semvar.outputs.changed }}
          git tag -a ${{ steps.semvar.outputs.version }} -m "tag version ${{ steps.semvar.outputs.version }}"
          git push origin ${{ steps.semvar.outputs.version }}
